database:
  username: postgres
  password: 1234pass
spring:
  application:
    name: horoscope-prediction
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/for_horoscope_db
    username: ${database.username}
    password: ${database.password}
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
  flyway:
    user: ${database.username}
    password: ${database.password}
    schemas: for_horoscope_db
    locations: classpath:db/migration
server:
  port: 9090